name: Build and deploy Python app to Azure Web App - sophia

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source depuis GitHub
      - uses: actions/checkout@v4

      # Étape 2 : Configurer la version de Python
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Étape 3 : Créer un environnement virtuel et installer les dépendances
      - name: Install dependencies
        run: |
          cd api
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Étape 4 (optionnel) : Ajouter une étape pour exécuter les tests
      # - name: Run tests
      #   run: |
      #     cd api
      #     source venv/bin/activate
      #     pytest

      # Étape 5 : Créer un fichier zip des fichiers nécessaires pour le déploiement
      - name: Zip artifact for deployment
        run: |
          cd api
          zip -r release.zip . \
          -x "venv/*" "*.git*" "*.github*" "__pycache__/*"

      # Étape 6 : Télécharger l'artefact pour le job de déploiement
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: api/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write # Requis pour demander un JWT

    steps:
      # Étape 1 : Télécharger l'artefact depuis le job de build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Étape 2 : Décompresser l'artefact
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Étape 3 : Connexion à Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Étape 4 : Déployer sur Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sophia'
          slot-name: 'Production'
